### ISSUE TITLE
How to visualize geometry?

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-g4ox#18]
Please try to add this to the main:

  **#include "G4VisExecutive.hh"
  #include "G4UIExecutive.hh"
  #include "G4UImanager.hh"**

Then just before 
**run_mgr->Initialize();**

add

```
G4UIExecutive *ui = 0;
G4VisManager *visManager = new G4VisExecutive("Quiet");
visManager->Initialize();
ui = new G4UIExecutive(argc, argv);
G4UImanager *UImanager = G4UImanager::GetUIpointer();
UImanager->ApplyCommand("/control/execute vis.mac");
ui->SessionStart();**
```

Then add this .mac file to where you run the code from:
https://drive.google.com/file/d/1ax-n_5DvemKYET9oHtcu7j2vcEn-VLyJ/view?usp=sharing

**Comment by ggalgoczi** [comment]
Also the visualization stuff needs to be added to the **CMakeLists.txt**:

`find_package(Geant4 REQUIRED ui_all vis_all)`

**Comment by plexoos** [comment]
Correct, the executable needs to link the appropriate Geant4 libraries... In CaTS they include everything using ${Geant4_LIBRARIES}

https://github.com/hanswenzel/CaTS/blob/5b262890dd6283baac0c49bbab85a8abef0fba97/CMakeLists.txt#L113C77-L113C96

**Comment by ggalgoczi** [comment]
Thanks Dmitri!

I found out why the visualization was not working.
`  run_mgr->Initialize();`

Needs to be called before:

` ui->SessionStart();` and   `visManager->Initialize();`

Please see attached the GUI with optical photons simulated:
https://drive.google.com/file/d/1wTbCoKP4jz5rtDJBp9IVy4abqgK6wsme/view?usp=sharing

**Comment by plexoos** [comment]
Great! Thank you very much for debugging it!
