### ISSUE TITLE
Optical photons originate outside pfrich model

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-g4ox#24]
./build/src/simg4ox -g geom/pfrich_opticks.gdml -i -m vis.mac

Am I calling it wrong? It yields this:

![image](https://github.com/user-attachments/assets/2442d095-fcef-466b-957d-230660459ae2)

**Comment by ggalgoczi** [comment]
That's all right, could you share what parameters you used for the plots in the meeting notes? I want to test reflectivity within the model.

**Comment by plexoos** [comment]
Sure, here they are:

```
torch.pos = {0.0f, 400.0f, -1400.0f};
torch.mom = {0.0f, +1.f, -0.1f};
```

**Comment by plexoos** [comment]
I think we can close this one? Looks like we have the torch under control
<img width="647" alt="Screenshot 2024-09-24 at 8 13 13 PM" src="https://github.com/user-attachments/assets/3ddc04b1-60cf-4a5c-9721-18d572590174">

**Comment by ggalgoczi** [comment]
Yes, adding the optical physics solved, the problem, let's close it.
