### ISSUE TITLE
Code organization on GPU/CPU

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-g4ox#28]
Understand how the code organized on different hosts. From one of the presentations it seems that simulation classes are defined separately.

![Screenshot from 2024-09-25 12-11-30](https://github.com/user-attachments/assets/c00c09c1-7397-4efd-a2cd-39385321b96e)

**Comment by ggalgoczi** [comment]
@plexoos your last commit 1b41e4b uses 

`sev = SEvt::HighLevelCreate(SEvt::ECPU);`

So the ray tracing lives on the CPU and not GPU. Is it correct?

In my understanding **SEvt::EGPU** is the GPU.

**Comment by plexoos** [comment]
I'm not entirely clear on the difference between these two values: EGPU and ECPU. It ultimately comes down to this section of the code:

https://github.com/BNLNPPS/esi-opticks/blob/68d5077f5de9cb31942308b0769a34b8c440131f/sysrap/SEvt.cc#L1040-L1049

From my perspective, there shouldn't be any difference whether you use ECPU or EGPU."

**Comment by ggalgoczi** [comment]
I just changed to SEvt::EGPU and got an error

simg4ox: /esi/opticks/sysrap/SEvt.cc:2227: void SEvt::hostside_running_resize(): Assertion `is_self_provider' failed.
Aborted (core dumped)

While  SEvt::ECPU worked without error.

Let me know if you get different results. Thanks!

**Comment by ggalgoczi** [comment]
It seems that we can choose whether to run CPU, GPU or both from the file you shared. Will keep digging:
```

    else if( integrationMode == 1 )   // GPU optical simulation only
    {
        CreateOrReuse(EGPU); 
    }
    else if( integrationMode == 2 )   // CPU optical simulation only 
    {
        CreateOrReuse(ECPU); 
    }
    else if( integrationMode == 3 )  // both CPU and GPU optical simulation
    {
        CreateOrReuse(EGPU); 
        CreateOrReuse(ECPU); 
    }
```

**Comment by ggalgoczi** [comment]
OPTICKS_INTEGRATION_MODE is the env variable that is supposed to set whether the simulation runs purely on GPU, CPU or both.

From sysrap/SEvt.cc 
else if( integrationMode == 2 )   // CPU optical simulation only 
else if( integrationMode == 3 )  // both CPU and GPU optical simulation

However runtime is almost the same. Needs further investigation.

**Comment by ggalgoczi** [comment]
Managed to get Opticks running on CPU instead of GPU. The magic trick is to call

`G4CXOpticks::NoGPU = true;`

I put this here for later use when performing testing. I called it just before:

`G4CXOpticks::SetGeometry(world);`

**Comment by ggalgoczi** [comment]
It seems G4CXOpticks photon simulation can not run on the CPU, since in
`G4CXOpticks::simulate`

we have 

`if(NoGPU) return ; `

what confused me was that the geometry translation is done even in this case :)
