### ISSUE TITLE
Raindrop geometry needs fixing

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-g4ox#33]
Need to add RIndex for all materials.
Need to add Efficiency if we want to get back Hits from Opticks (GPU).
Need to remove RIndex from the optical boundary as it is a property of material not the boundary.

**Comment by plexoos** [comment]
Is there an easy way to reproduce the issue?

**Comment by ggalgoczi** [comment]
For CaTS yes, but since there is no repo here it is not easy. I can create a new repo and upload my code.

**Comment by ggalgoczi** [comment]
Uploaded a new raindrop geometry that includes RINDEX and sensitive detector flag for Opticks.
