### ISSUE TITLE
Reading in (standalone) pfRICH complex geometry into Opticks fails

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-g4ox#41]
Opticks can not work with G4Trap and G4Trd volumes used in the [pfRICH standalone model.](https://github.com/BNLNPPS/esi-g4ox/blob/main/geom/pfRICH_complex.gdml) I get the following error:

```
U4Solid::init_Check FAILED desc:   0/3/ level -1 entityType           G4Trap name FlangeWedge
CaTS: /usr/local/opticks/include/U4/U4Solid.h:443: void U4Solid::init_Check(): Assertion `0' failed.
```

**Comment by ggalgoczi** [comment]
Tried two solutions:
-- Force Opticks to triangulate these volumes by setting the **stree__force_triangulate_solid** env variable. Did not work.
-- Changing Trd and Trap volumes in the GDML to boxes. 

In the latter case got:

```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomSolids2001
      issued by : G4BooleanSolid::StackPolyhedron()
Solid - BelleIIAerogel3-0-00 - No G4Polyhedron for Boolean component
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

Segmentation fault (core dumped)
```

**Comment by ggalgoczi** [comment]
In the latter case it is likely that I introduced overlaps by using smaller boxes than the original trd and trap volumes. 

@plexoos  do you have an idea how to fix this?

**Comment by plexoos** [comment]
Before we try to deal with this geometry in Opticks, have you checked that it can be visualized in Geant4?
It did not work for me... But I was able to open it in ROOT

**Comment by ggalgoczi** [comment]
The problem is with visualization not the model.

OpenGL and QT can not visualize some boolean solids in this file... The Geant4 devs recommend using RayTracerX and when I tried to use it, it did work (but can not rotate the geometry interactively).

https://geant4-forum.web.cern.ch/t/error-in-geometry-made-by-boolean-operations/6218/10

Could you try to replace trap and trd with boxes? I tried it but did not work for me. An other option is to just turn off visualization for the problematic volumes.

**Comment by ggalgoczi** [comment]
I managed to solve the visualization issue for Geant4. (Not Opticks!) I will push the solution to the repo.

I will not close this issue because this issue is about reading in the volume into Opticks.

**Comment by plexoos** [comment]
> I will push the solution to the repo.

Yes, please create a PR. I am really curious what those mirror pyramids are and what they represent

**Comment by plexoos** [comment]
> Could you try to replace trap and trd with boxes?

I don't think I would do it any different from what you've tried. If you don't mind, please share your modifications on a branch like I did for the reflectivity study https://github.com/BNLNPPS/esi-g4ox/compare/main...raindrop-reflectivity-studies

**Comment by ggalgoczi** [comment]
I do not understand. This last screenshot. Is it with the full pfRICH model? You mention that you defined optical surfaces in the standalone full model but they are there already.

 It should look very different, like this:

![Screenshot from 2024-10-15 19-01-52](https://github.com/user-attachments/assets/89f08b68-bbff-4b00-8cc3-008d77ccc972)

I will create a PR for the Geant4 visualization problem for the standalone version.

**Comment by plexoos** [comment]
No, I simplified the full `pfRICH_complex` model to keep only some volumes

**Comment by ggalgoczi** [comment]
So is your plan to include only the sensitive volumes besides what you have?

At some point we will need to include the full geometry. I would rather attack this problem and get over it if possible. I do not see any other way around then coding the G4Trap stuff into Opticks ourselves. What do you think?

**Comment by plexoos** [comment]
Yes, I'm trying to find the least common denominator in the pfRICH geometry so that it can be used by both G4 and Opticks. The CSG tree is built using this simple G4 feature: https://github.com/BNLNPPS/esi-opticks/blob/esi/u4/U4Mesh.h#L195-L201, which clearly only works for volumes with rotational symmetry. I think this is why it fails with G4Trap and G4Trd.

**Comment by ggalgoczi** [comment]
I created a PR to include hiding of subtraction volumes from Geant4 vis. Should have been a different issue in hindsight.

**Comment by ggalgoczi** [comment]
> Yes, I'm trying to find the least common denominator in the pfRICH geometry so that it can be used by both G4 and Opticks. The CSG tree is built using this simple G4 feature: https://github.com/BNLNPPS/esi-opticks/blob/esi/u4/U4Mesh.h#L195-L201, which clearly only works for volumes with rotational symmetry. I think this is why it fails with G4Trap and G4Trd.

That is correct but if we implement these volumes, then Opticks will use them. Here you can see the currently supported volumes:

https://github.com/BNLNPPS/esi-opticks/blob/esi/u4/U4Solid.h#L415-430

So do you agree we need to implement G4Trap? About G4Trd I am not sure since there is only one instance of the latter.

**Comment by plexoos** [comment]
> then Opticks will use them

How do we make sure that Opticks is using them? When I save the CSG into files I see only meshes...

**Comment by ggalgoczi** [comment]
When you asked why "G4Trap" can not be read into Opticks on their forum, the Opticks dev recommended to implement it and then it will work:

https://groups.io/g/opticks/message/515?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3Arelevance%2C%2Cg4trap%2C20%2C2%2C0%2C104211135

Regarding your question how we can make sure Opticks uses them I do not know yet, will have to look into it later.

**Comment by ggalgoczi** [comment]
The reason for the failure was found, hence closing this.
