### ISSUE TITLE
Implement Opticks hits

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-g4ox#54]

**Comment by ggalgoczi** [comment]
@plexoos  I implemented the Optickshits in a7a2e2e .

However after I run the GPU simulation I do not get any hits from GPU. I do get hits for the same "detector" from the Geant4 simulation.

Do you know how to check if said photons actually ran on the GPU?

**Comment by ggalgoczi** [comment]
Update: I forgot to mention when you test this with 

`esi-g4ox/geom/opticks_raindrop.gdml`

the photon position needs to be set to 0 0 0 in simtox to get G4Hits in esi-g4ox.

**Comment by ggalgoczi** [comment]
The branch [OpticksHits](https://github.com/BNLNPPS/esi-g4ox/tree/OpticksHits) contains a working example of how to pass gensteps to GPU and get back the hits. For now every genstep is simulated one by one, will make it smarter.

The commands to run this example:

```
QCurandState_SPEC=3:0:0 /usr/local/opticks/lib/QCurandStateTest
cmake -S esi-g4ox -B build
cmake --build build
export OpticksGDMLPath= /esi/esi-g4ox/geom/simplelar.gdml
./build/src/simg4ox -g /esi/esi-g4ox/geom/simplelar.gdml -m esi-g4ox/run.mac
```

**Comment by ggalgoczi** [comment]
Ran the [OpticksHits](https://github.com/BNLNPPS/esi-g4ox/tree/OpticksHits) branch with 50 MeV electron and the newly added pfrich_min_irrealistic_rindex.gdml geometry. Added rindex to all materials, efficiency to the detector surface. Got roughly ~50 hits after Opticks GPU simulation. In the attached screenshot reflections can be seen. The added refractive indices are irrealistic, need to work on that. 

An example hit: <wavelength> <position> <direction>  <polarization>  

Adding hit from Opticks: 279.395 (-224.5,-4.14182,178.006) (-0.998298,-0.0446274,0.0375544) (0.0337258,0.0836507,0.995924)

![Screenshot from 2024-11-23 12-48-25](https://github.com/user-attachments/assets/8102e3f4-f22c-4ff6-ad01-4446ff22fc01)

**Comment by ggalgoczi** [comment]
Adding comments here as a reminder from Simon:

> 
> Because of this comparison there are two SEvt instances
> to be aware of (with enum EGPU:0 and ECPU:1).
> 

```
> 
> unsigned num_hits_gpu = SEvt::GetNumHit(EGPU);
> unsigned num_hits_cpu = SEvt::GetNumHit(ECPU);
>        
```

> 
> It's better to use the _ECPU() _EGPU() methods or the enum to be
> clearer.

**Comment by plexoos** [comment]
But we still don't see hits with g4ox, correct?

**Comment by ggalgoczi** [comment]
I did see hits with gensteps, input photonlist and torch too. I have an additional branch where I implemented torch. I will create an other branch about gensteps!
